- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/mesh.py
Very small fix to streamline the xrange and izip differences between Python 2 and 3.
I don't know why this PR is also including the is_valid commit because this has already been merged in.
> fix(face): Cleaning up Python 2/3 code

- ladybug_geometry/__init__.py
- setup.cfg
- setup.py
The version for PyPI was set to the hard-coded version in \__init__.py. This is now fixed.
> fix(deploy): use semantic release for deployment to PyPI

- ladybug_geometry/_mesh.py
- ladybug_geometry/geometry2d/_1d.py
- ladybug_geometry/geometry2d/_2d.py
- ladybug_geometry/geometry2d/line.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry2d/ray.py
- ladybug_geometry/geometry3d/_1d.py
- ladybug_geometry/geometry3d/_2d.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/line.py
- ladybug_geometry/geometry3d/mesh.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- ladybug_geometry/geometry3d/ray.py
The previous implementation of __slots__ was not correct across the inheritance tree.  So it was not doing anything for the vast majority of geometry objects.  This commit fixes this.
In the process, I realized that I had to give up the dual inheritance of Mesh objects since both of the objects it had previously inherited from have a `vertices` attribute.  However, this hasn't increased the extra code by any more than 100 lines and is a small price to pay for the functionality of __slots__.
> perf(slots): Fixed the Implementation of __slots__ in Inheritance

- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry3d/pointvector.py
As noted in other discussions, I realized that this did not significantly affect the performance of initializing objects with a lot of points.  So we might as well implement this and avoid having to check it elsewhere.
> feat(point): Added automatic casting to float for coordinate values

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/polyface.py
@mostaphaRoudsari ,  I just wanted to make you aware of this change since this affects the `overhang` and `fin` methods that are currently in `honeybee-core` PR.  I realized that the tolerance for generating fins before this PR was 0, which basically resulted in very small overhangs being generated whenever the generating face did not have a flat top.  This means that you would always get an overhang with the previous code. This PR solves this by adding a tolerance input and also seems to give a better solution to the case we discussed of potentially warning the user about every aperture in their model that does not have a flat top.
Rather than trying to take care of everything for the user in one method and potentially making them read a bunch of warnings that may not have much meaning …
> feat(contour): Adding input for tolerance to contour methods

- ladybug_geometry/geometry3d/polyface.py
- tests/polyface3d_test.py
These really didn't have to be separate methods and, after I ran some performance tests, there was virtually no difference between these two approaches that would justify having them as separate.  To quote the Zen of Python:
There should be one-- and preferably only one --obvious way to do it.
@mostaphaRoudsari , once you approve this, I will do a new official release of `ladybug_geometry`.
> style(polyface): Wrapped from_faces_tolerance into from_faces

- ladybug_geometry/geometry3d/polyface.py
- tests/polyface3d_test.py
Small fix to ensure that mesh grids that are generated from a box floor are correctly oriented to the box plane.
> fix(polyface): Ensuring that from_box preserves base_plane orientation

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
The word "check" is a lot more generic and easier to remember than "validate".  So I changed all of the checking functions in honeybee-core to use the word "check" instead of "validate".  Now I am changing ladybug-geometry to follow the same convention.
> style(face3d): Changing validate_planarity to check_planar

- .releaserc.json
- .travis.yml
- deploy.sh
This commit is trying to bring this repo in sync with the structure of the ladybug tool template repo. It's taking a cue from [this commit here](https://github.com/ladybug-tools/honeybee-core/commit/deeb42245bf83a168d9440fcff3ad3bf8aafa39f).
We can hold off on merging this PR until we get confirmation that I did this correctly on [this PR](https://github.com/ladybug-tools/ladybug-comfort/pull/38) and santiago's PR gets merged and I bring this fork in sync with his changes.
> fix(docs): build docs in separate step to PyPi deployment

- ladybug_geometry/geometry2d/_2d.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry3d/_2d.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/line.py
- ladybug_geometry/geometry3d/pointvector.py
- tests/face3d_test.py
The calculation was producing vectors with 0 magnitude in the case that the first 3 vertices were co-linear.
I also fixed a few other bugs that were found by the VScode linter.
> fix(face): Fix automatic normal calculation in Face3D

- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- tests/face3d_test.py
- tests/pointvector2d_test.py
- tests/pointvector3d_test.py
- tests/polyface3d_test.py
Without a tolerance input for the Face3D plane auto-calculation, the plane normal was completely incorrect in some cases where the planarity of the Face3D differed by a small amount. This commit should fix this by exposing an option to input a tolerance when the input Plane is None.
This bug is really critical, @mostaphaRoudsari , and I want to find out which of the other libraries are affected by it as soon as I can so I am just going to merge it in.
> fix(face): Fixed bug in Face3D plane normal

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/polyface.py
- tests/face3d_test.py
- tests/polyface3d_test.py
I realized that there is a way to address the previous critical tolerance bug without changing all of the libraries that use the Face3D class. It's ever so slightly less efficient than what I had previously but it's WAAAY more elegant and beautiful.
As the first and most important tenant of Python Zen states:
"Beautiful is better than ugly."
Also, I promise this is my last commit to this repo for the day (I am sorry for pushing so many edits in a short period of time)
> fix(face): Implement most beautiful solution for tolerance issue

- ladybug_geometry/geometry2d/line.py
- ladybug_geometry/geometry3d/line.py
- tests/line3d_test.py
This commit fixes a Python tolerance issue that can sometimes arise in the LineSegment.subdivide_evenly method. I was only able to find this one after testing it on several thousand line segments in Rhino. Glad that this bug is squashed!
> fix(line): Fix bug in LineSegment.subdivide_evenly method

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
Added alternate method on Face3D class to generate rectangular glazing from a base rectangular surface using a height and width, porting original Javascript code to Python. Also added tests to confirm that new Face3D class method is working properly.
Fixes #54
> Added alternate method for generating Face3D sub-faces

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/line.py
- tests/face3d_test.py
It seems the previous commit wasn't built to handle any rectangle except one at the origin in the XY plane. This commit fixes it and adds a more public method that can be used to generate sub-faces for a given parent Face3D.
It seems the docstrings in the previous merge were also not correct and these are fixed now.
> fix(face3d): Fix sub_faces_by_dimension_rectangle method

- ladybug_geometry/geometry3d/cone.py
- ladybug_geometry/geometry3d/cylinder.py
- ladybug_geometry/geometry3d/sphere.py
- ladybug_geometry/intersection3d.py
- tests/cone_test.py
- tests/cylinder_test.py
- tests/sphere_test.py
Hi @chriswmackey,
I added a initial class for the cylinder for your review. This object is inspired in the cone in terms of its definition. Please let me know if that makes sense, 
In regards to naming, I am not sure if the '_center' name is the most correct one here.  It is actually the bottom base center of the cylinder but I'm trying to keep it simple if that makes sense.
Please let me know also if I should add any additional methods/properties to it.
> Add Cylinder3D

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/polyface.py
- tests/face3d_test.py
It seems we needed one final check to be sure that the point we use to test the face's orientation is truly on the face. This fix makes the method capable of catching cases of wide convex angles.
> fix(polyface): Fix method ensuring outward faces

- ladybug_geometry/geometry3d/plane.py
It seems this was too strict for typical Rhino tolerances and we should really only raise an error when the angle is clearly off the mark.
> fix(plane): Loosen restrictions of X-axis check

- ladybug_geometry/geometry2d/polygon.py
- tests/polygon2d_test.py
This commit fixes an issue where new points of the Polygon2D intersection calculation were not being placed back in the correct order of their parent Polygon.
It adds a new hidden method, which ensures that multiple updates to a single segment are inserted in the correct order over the polygon.
> fix(polygon): Correctly sort Polygon2D intersection points

- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- tests/face3d_test.py
- tests/pointvector2d_test.py
- tests/pointvector3d_test.py
- tests/polyface3d_test.py
There really shouldn't be any case where a tolerance of 0 is used. So I am removing it as a default input across the library.
Resolves https://github.com/ladybug-tools/ladybug-geometry/issues/89
> fix(tolerance): Require input of tolerance and do not use 0

- ladybug_geometry/geometry2d/line.py
- tests/line2d_test.py
@chriswmackey 
I'd like to add this is_equivalent method to the LineSegment2D object. Note that order of the points doesn't matter for equivalence to be True.
> feat(LineSegment2D): Add is_equivalent method to line2d and tests.

- ladybug_geometry/bounding.py
- tests/bounding_test.py
- tests/polyface3d_test.py
This commit adds a module for computing bounding boxes and rectangles around arrays of ladybug geometry, which I have come to realize is something that's needed throughout several of the core libraries.
Resolves https://github.com/ladybug-tools/ladybug-geometry/issues/173
> feat(bounding): Add a module to compute bounding boxes

- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry3d/mesh.py
- tests/mesh3d_test.py
Given that all tuples get cast to a list with JSON serialization, the Mesh.from_dict methods need to handle the casting of these lists back to tuples for the mesh face indices.
> fix(mesh): Handle the case of lists describing mesh faces

- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry3d/mesh.py
- tests/mesh2d_test.py
- tests/mesh3d_test.py
It seems that I missed this the first time around. I have tested it from Rhino and I can now say that it's working.
> fix(mesh): Fix missing line of code in join_meshes

- ladybug_geometry/geometry3d/polyface.py
Colinear vertices were causing a failure in the calculation that flips all faces to point outwards from a solid Polyface. This extra check will make sure the flipping happens in the right direction.
> fix(polyface): Catch the case of colinear vertices in a solid

- ladybug_geometry/geometry2d/mesh.py
Reason being is that _quad_to_triangles return 0 based indices. These indices have to be re-adjusted to match the indices in the "face" object
> Fix Mesh2D Triangulation for four-vertex faces

- ladybug_geometry/geometry2d/polyline.py
- ladybug_geometry/geometry3d/polyline.py
- tests/polyline2d_test.py
- tests/polyline3d_test.py
I have come to realize that this will make a lot of my code that's higher in the dependency tree a lot cleaner, even though it's technically not necessary.  It's just that there are more cases where I have a mix of polylines and line segments than I originally realized.
> fix(polyline): Add properties to easily access polyline endoints

- ladybug_geometry/geometry3d/mesh.py
- tests/mesh3d_test.py
I know that I originally put this code here to save time but it is definitely buggy and, in the grand scheme of things, it's more important that the joining of meshes be reliable than having to wait a few extra seconds at most to regenerate face normals.
> fix(mesh): Force the regeneration of normals after joining

- .dependabot/config.yml
- dev-requirements.txt
We really don't need these to be at the bleeding edge, especially when the latest versions of them conflict with one another.
> chore(deps-dev): Simplify updates of dev dependencies

- ladybug_geometry/geometry3d/face.py
Technically, these faces are invalid but we should still serialize them so that we can report errors related to them.
> fix(face): Prevent failure in the case of a sliver faces

- .gitignore
- ladybug_geometry/dictutil.py
- tests/dictutil_test.py
Adds a new converter function to ladybug_geometry. Similar to the existing 'dictutil' for Honeybee. Takes in a dict and converts to back Ladybug Geometry Object (reverses the .to_dict method). Includes unit tests.
> Ladybug Geometry 'dictutil' converter function

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
It seems that the remove_colinear_vertices method would remove the last vertex twice if those last two vertices were equivalent to one another. This is not necessarily what you want unless both of those last two vertices are colinear with the vertices surrounding it. This commit fixes this case.
> fix(face): Avoid removing the last vertex twice

- ladybug_geometry/geometry3d/face.py
It seems that duplicate/colinear vertices can interfere with the calculation of points on the face.  This fix ensures that this calculation always happens with a list over vertices that includes no duplicates and no colinear vertices.
> fix(face): Ensure duplicate vertices don't interfere with outward calc

- ladybug_geometry/geometry2d/arc.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry2d/polyline.py
- ladybug_geometry/geometry3d/arc.py
- ladybug_geometry/geometry3d/cone.py
- ladybug_geometry/geometry3d/cylinder.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/mesh.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- ladybug_geometry/geometry3d/polyline.py
- ladybug_geometry/geometry3d/sphere.py
- tests/face3d_test.py
- tests/pointvector3d_test.py
This commit adds methods to get the bounding polygon corners around Face3Ds. It also improves the reliability of the upper_left_counter_clockwise_vertices method in the case where the Y-axis is not verticel.
> fix(face): Add property and methods to get Point2Ds in a Face3D plane

- ladybug_geometry/geometry2d/line.py
- tests/line2d_test.py
- tests/line3d_test.py
It seems that colinear segments that do not overlap will return an intersection if they are colinear to within Python floating point tolerance.
Adding a check for a negative zero seems to catch this case while leaving all others undisturbed.
> fix(line): Add a test for signed zeros in line 2D intersection

- ladybug_geometry/geometry3d/face.py
It turns out that preserving the plane information while scaling can disrupt some things in cases where we transfer plane information from the CAD interface.
More information is here:
https://discourse.ladybug.tools/t/louvershades-vertical-option-bug/17620
> fix(face): Reset the Face3D plane information when scaling

- ladybug_geometry/geometry2d/polygon.py
- tests/face3d_test.py
This will prevent the pole_of_inaccessibility() function from looping endlessly.
> fix(polygon): Add an extra check for degenerate geometry

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- tests/polygon2d_test.py
This should finally fix the fact that honeybee has not been able to identify self-intersecting Face3Ds.
We're also changing the Polygon2D.is_self_intersecting method to be true to the real shape regardless of whether it was created with the from_shape_with_hole method. This seems like a more honest way of dealing with Polygons were the boundary has been merged into the holes.
> fix(face): Ensure that self-intersection check happens for each loop

- ladybug_geometry/intersection2d.py
It seems that math.isclose was not introduced until Python 3.5. So we need this in order for things to work in Ironpython 2.7.
> fix(intersection): Replace math.isclose with Python 2 compatible code

- ladybug_geometry/geometry2d/polygon.py
- tests/polygon2d_test.py
This way, the results can be filtered without having to recompute the axes. This also gets the resulting axes to be closer to the best common axis across the segments rather than loosing accuracy by averaging the groups.
> fix(polygon): Improve common_axes method to return each axis value

- ladybug_geometry/_mesh.py
- ladybug_geometry/geometry3d/mesh.py
- tests/mesh3d_test.py
Adding a new [Mesh3D](https://github.com/ladybug-tools/ladybug-geometry/blob/0cffcb59d62d951286d837ac4c536d85e064c9b1/ladybug_geometry/geometry3d/mesh.py#L18) creation classmethod. 
Create a new Mesh3D from face-vertices and use the vertices' [`is_equivalent`](https://github.com/ladybug-tools/ladybug-geometry/blob/0cffcb59d62d951286d837ac4c536d85e064c9b1/ladybug_geometry/geometry3d/pointvector.py#L123) to check for duplicate vertices. Similar to using [`from_face_vertices(..., purge=True)`](https://github.com/ladybug-tools/ladybug-geometry/blob/0cffcb59d62d951286d837ac4c536d85e064c9b1/ladybug_geometry/geometry3d/mesh.py#L104C9-L104C27), but allows for tolerance when checking vertices against one another. 
For background, see: https://discourse.ladybug.tools/t/unexpected-result-creating-mes …
> fix(mesh): Add Mesh3D constructor with tolerance check

- ladybug_geometry/geometry2d/polygon.py
This should help ensure the method gives more accurate results when removing colinear vertices at a tolerance that is 6 significant figures smaller than the polygon vertices.
The method essentially corrects for the "area of triangle" assumption that we use, dividing this area by 2 to relate it to the height of the triangle (aka. distance from collinearity). Also, we account for the fact that multiple skipped vertices compound this area, meaning that, with a lot of skipped vertices, there's a chance that some should be kept.
> fix(polygon): Improve tolerance with removing colinear vertices

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/intersection2d.py
This is needed for when the coordinates are very close to zero.
> fix(intersection): Use an absolute tolerance for 2D line intersection

- ladybug_geometry/network.py
It seems like the "signed zero" issue is a little more complex than I thought given that you can have coordinate values like -0.002 and +0.002. Both of these should get a value of 0 in their coordinates hash if the tolerance is 0.01. But one will get a singed zero (-0) unless we do an extra check for this.
> fix(network): Ensure negative coords less than tol read as 0 and not -0

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
It seems that the function to remove colinear vertices was too aggressive in some cases and was not aggressive enough in other cases. This is because the criteria to evaluate whether a given vertex is colinear did not account for the distance between the neighboring vertices.
Now, a colinear vertex will only be removed if the distance between it and the line drawn between the two neighboring vertices is less than the tolerance.
> fix(polygon): Respect tolerance when removing colinear vertices

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
This will be used in the importers from IDF, OSM, and gbXML, which all represent Faces with a single flat list of vertices.
> fix(face): Add a method to separate Face3D boundary and holes

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/mesh.py
All of the copy methods really aren't needed since geometry objects are immutable but I can see they might be useful for certain types of advanced editing of underlying properties (that users do at their own peril).
So I'll just leave them as they are and make sure that they work.
Resolves https://github.com/ladybug-tools/ladybug-geometry/issues/404
> style(face): Implement better __copy__ method

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/polyface.py
We should be making sure that the _point_on_face is more than the tolerance away from any edge if we want it to work consistently with the tolerance specified in the other routines that use it.
> fix(face): Improve accounting for tolerance in room solidity routine

- ladybug_geometry/geometry2d/polygon.py
- tests/polygon2d_test.py
This commit also exposes a new option for getting common axes as near-centerlines between polygon edges.
> fix(polygon2d): Fix edge case bug in Polygon.group_by_touching

- ladybug_geometry/geometry2d/mesh.py
- tests/face3d_test.py
We were getting exceptions raised in the case that a Face3D with zero area was used to make a triangulated_mesh3d.
I think the logic follows that, if we allow for the creation of a Face3D with zero area, we should similarly allow it's triangulated Mesh3D to exist with zero area.
> fix(mesh): Ensure that triangulated_mesh3d never raises exception
