- ladybug_geometry/_mesh.py
- ladybug_geometry/geometry2d/_1d.py
- ladybug_geometry/geometry2d/_2d.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/_1d.py
- ladybug_geometry/geometry3d/_2d.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/mesh.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- tests/face3d_test.py
- tests/line2d_test.py
- tests/line3d_test.py
- tests/mesh2d_test.py
- tests/mesh3d_test.py
- tests/plane_test.py
- tests/pointvector2d_test.py
- tests/pointvector3d_test.py
- tests/polyface3d_test.py
- tests/polygon2d_test.py
- tests/ray2d_test.py
- tests/ray3d_test.py
There are also a few minor tweaks here like a bug fix to the Plane `__init__` method and the exposing of a staticmethod on Polyface3D to get outward-facing faces.
>  feat(dict): Adding to_dict and from_dict methods to all geometry obects

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
This is a very minor change but I just wanted to push it since, after thinking about it, I am pretty sure that this is how we should be solving for adjacency.
I am also sending this because I wanted to see how the new setup works if we only keep a master branch on our fork, sync it with the ladybug tools master, and we send our PRs to the ladybug tools development branch.  After doing this, I see that it includes your previous commit, @mostaphaRoudsari  (though it would not do this if I sent the PR directly to ladybug tools master).  Did I not set this up correctly, @mostaphaRoudsari ?  Should I be syncing my fork's master with ladybug tools development branch and not ladybug tools master?
> feat(face3d): Adding method for is_centered_adjacent 

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
@mostaphaRoudsari ,
Why does it now add your extra commit to this PR?  Did I make a mistake somewhere? Should I have not doe "Rebase and Merge" when I merged in the last PR to development?
>  feat(face3d): Adding method for is_centered_adjacent

- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/polyface.py
- tests/face3d_test.py
- tests/polyface3d_test.py
- tests/polygon2d_test.py
... and I added in a few methods to transfer properties between the old and new objects.
> feat(face): Enforcing counterclockwise vertices for all Face3D

- ladybug_geometry/geometry3d/face.py
- tests/arc2d_test.py
- tests/arc3d_test.py
- tests/face3d_test.py
- tests/line2d_test.py
- tests/line3d_test.py
- tests/mesh2d_test.py
- tests/mesh3d_test.py
- tests/plane_test.py
- tests/pointvector2d_test.py
- tests/pointvector3d_test.py
- tests/polyface3d_test.py
- tests/polygon2d_test.py
- tests/ray2d_test.py
- tests/ray3d_test.py
Very small PR here.  Just a change that I realized should be made to a method to make it suitable for solve adjacencies.
> feat(face3d): Improving is_centered_adjacent method for honeybee solve adjacencies

- ladybug_geometry/geometry2d/_1d.py
- ladybug_geometry/geometry2d/arc.py
- ladybug_geometry/geometry2d/line.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry2d/ray.py
- ladybug_geometry/geometry3d/_1d.py
- ladybug_geometry/geometry3d/arc.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/line.py
- ladybug_geometry/geometry3d/mesh.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- ladybug_geometry/geometry3d/ray.py
This one puts the schema in line with what we discussed today @mostaphaRoudsari .
> style(dict): Changing the dict schema of all geometry objects

- ladybug_geometry/geometry2d/_1d.py
- ladybug_geometry/geometry2d/arc.py
- ladybug_geometry/geometry2d/line.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry2d/ray.py
- ladybug_geometry/geometry3d/_1d.py
- ladybug_geometry/geometry3d/arc.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/line.py
- ladybug_geometry/geometry3d/mesh.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- ladybug_geometry/geometry3d/ray.py
- tests/polyface3d_test.py
honeybee-core needs the new dictionary schema of the geometry objects so I am doing another release now.
> Syncing Master with Development for Another Release

- ladybug_geometry/geometry3d/face.py
This option will be used by honeybee-core to ensure the Face3D is always written with vertices starting from the upper left when it is exported for energy simulation.
> feat(face): Adding option for upper-left vertices in Face3D.to_dict()

- ladybug_geometry/geometry2d/polygon.py
- tests/polygon2d_test.py
I have added a static method to the Polygon2D class to perform intersection analysis on adjacent polygons.
> Updated polygon class with static method to perform intersection analysis on adjacent 2D polygons.  Updated unit tests as well

- ladybug_geometry/geometry2d/polygon.py
- tests/polygon2d_test.py
It seems the tolerance was not being interpreted correctly. I also cleaned up the code to obey our max line length of 89 characters.
Lastly, I realized that we were missing an init.py in the tests folder, which was stopping pytest from running correctly in Python 2.
@mostaphaRoudsari , I am just going to merge this one in as it's a small fix to some code that was recently committed.
> fix(intersect): Fix intersection method between Polygon2D

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/polyface.py
- tests/polyface3d_test.py
- tests/polygon2d_test.py
This PR also exposes some of the previously hidden useful functions on the Polygon2D. It also adds a bounding box checking method to the Polyface3D class.
If you don't mind, @mostaphaRoudsari , I am just going to merge this one in without review since I need the bug fix to continue working on the grasshopper end.
> fix(face3d): Fix bug in is_centered_adjacent

- ladybug_geometry/geometry3d/polyface.py
The previous bug had a bit of a larger scope than I realized but I think that this should address it. Unfortunately, this means that the tolerance is needed to re-create the Polyface3D to its original state whenever it's re-serialized from_dict. This also means that honeybee Rooms and Models have this restriction and I am going to add tolerance inputs to those classmethods as well. However, this is much more preferable to being forced to have incorrect Face normals, which is what we would have to do previously. I'll use a default tolerance of 0 so that people aren't always forced to supply it if they don't care about Face normals or they actually have made a model that is good down to 0 tolerance.
> fix(poltface): Fix tolerance issue within the Polyface3D class

- ladybug_geometry/geometry2d/line.py
- ladybug_geometry/geometry3d/line.py
I realized there is a slightly more elegant way to address the previous bug.
> fix(line): Implement more elegant solution to previous fix

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
I discovered several bugs in the Face3D contouring methods while making use of them with Rhino geometry. This commit should address all that I found.
> fix(face): Fix several bugs in Face3D contour methods

- ladybug_geometry/geometry2d/_1d.py
- ladybug_geometry/geometry2d/_2d.py
- ladybug_geometry/geometry2d/arc.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/_1d.py
- ladybug_geometry/geometry3d/_2d.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/mesh.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
Hi @chriswmackey,
Still not confident with GitKraken,  I ended up copying the files with the changes to desktop, deleting and re-forking the repo, and overwriting it with the changed files.
What I don't like is that the diffs are entire files as opposed to the changes only.  Is this because of the override? 
Hope this still works, let me know!
> Change to_dict and from_dict methods using Point arrays to use a to_array and from_array method on the Point classes #77

- ladybug_geometry/geometry3d/cone.py
- tests/cone3d_test.py
Happy New Year @chriswmackey, Sorry it took that long to get back to this, very excited to be back!
As you suggested I did clean up the fork and started a new PR with an initial Cone3D class for your review. 
When you get a chance please let me know your thoughts about constructor parameters as well as the properties included. Also feel free to add any functionality that may be useful to have in this geometry object.
> Add Cone3D

- ladybug_geometry/_mesh.py
- ladybug_geometry/geometry2d/_1d.py
- ladybug_geometry/geometry2d/_2d.py
- ladybug_geometry/geometry2d/line.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry2d/polyline.py
- ladybug_geometry/geometry2d/ray.py
- ladybug_geometry/geometry3d/_1d.py
- ladybug_geometry/geometry3d/_2d.py
- ladybug_geometry/geometry3d/arc.py
- ladybug_geometry/geometry3d/cone.py
- ladybug_geometry/geometry3d/cylinder.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/line.py
- ladybug_geometry/geometry3d/mesh.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/pointvector.py
- ladybug_geometry/geometry3d/polyface.py
- ladybug_geometry/geometry3d/ray.py
- ladybug_geometry/geometry3d/sphere.py
- tests/polygon2d_test.py
- tests/polyline2d_test.py
This commit adds a class for Polyline2D, including a method to join line segments into polylines, which will be critical for making correct geoJSON footprints in dragonfly for stories with several Rooms.
> feat(polyline): Add class for Polyline2D

- ladybug_geometry/_polyline.py
- ladybug_geometry/geometry2d/arc.py
- ladybug_geometry/geometry2d/polyline.py
- ladybug_geometry/geometry3d/_1d.py
- ladybug_geometry/geometry3d/arc.py
- ladybug_geometry/geometry3d/line.py
- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/polyline.py
- tests/arc3d_test.py
- tests/line3d_test.py
- tests/plane_test.py
- tests/polyline3d_test.py
This commit adds a class for 3D polylines, complete with methods for intersecting/splitting them with planes and joining segments into Polylines.
> feat(polyline3d): Add module and class for Polyline3D

- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/pointvector.py
I'm really sorry that I did not catch this bug sooner since it may have repercussions throughout the other libraries. Better to find them out now before the release, though.
> fix(point): Correction to Point __add__ and __sub__ operators

- ladybug_geometry/_polyline.py
I found a minor bug in the functions used by join_segments.
> fix(polyline): Fix minor bug in Polyline edge case

- ladybug_geometry/geometry2d/arc.py
- ladybug_geometry/geometry3d/arc.py
- tests/arc2d_test.py
- tests/arc3d_test.py
This will be useful for both climate graphics and for the planarization ob objects like the cylinder.
> feat(arc): Add to_polyline methods to the Arc classes

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
- tests/mesh2d_test.py
- tests/polyface3d_test.py
This will be useful for generating skylights.
> feat(face): Add sub_faces_by_ratio_gridded to Face3D

- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry3d/mesh.py
- tests/mesh2d_test.py
- tests/mesh3d_test.py
I realized that this is useful for a range of things. Notably, joining multiple meshes generated from Room floors when there are multiple floor Faces.
> feat(mesh): Add methods to join meshes into one

- ladybug_geometry/geometry3d/polyface.py
This is another bug fix that was exposed thanks to the previous bug fix.
> fix(polyface): Remove under-the-hood zero tolerance

- ladybug_geometry/_mesh.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry3d/mesh.py
- tests/mesh2d_test.py
- tests/mesh3d_test.py
We can just convert this to 'None' under the hood.
> fix(mesh): Handle the case that a user passes an empty list

- ladybug_geometry/_mesh.py
This one has slipped through the radar until now.
> fix(mesh): Fix bug in transferring of mesh properties with scale

- LICENSE
- setup.py
This commit should trigger a new build with an AGPL license for all the ladybug tools libraries.
> fix(license): update to AGPL

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/polyface.py
Now, we apply the same function to make sure that we have a test point that lies on the face as we do for the Polyface3D class when solving for outward-pointed faces.
> fix(face): Fix bug in centered adjacent for concave faces

- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- tests/mesh2d_test.py
This still doesn't totally solve the issue but it's an improvement and it prevents the method from completely failing.
> fix(mesh): Fix edge case issue in mesh triangulation

- docs/conf.py
Hey @chriswmackey,
I missed adding the sphinx-click plugin in the ``conf.py`` extensions list, please merge the update when you get a chance!
> docs(sphinx-conf): Add sphinx-click plugin

- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
Resolves https://github.com/ladybug-tools/ladybug-geometry/issues/301
> fix(face3d): Fix incorrect spelling of the word contour

- ladybug_geometry/geometry2d/pointvector.py
- ladybug_geometry/geometry3d/pointvector.py
We might as well us inheritance here.
> style(pointvector): Support is_equivalent for Vectors

- ladybug_geometry/geometry3d/plane.py
- ladybug_geometry/geometry3d/polyface.py
- tests/plane_test.py
I'm also editing the polyface object to preserve the properties of the original faces.
> fix(plane): Flipping plane should preserve X-axis

- ladybug_geometry/geometry3d/face.py
It seems that this is pretty fundamental to the translation to other geometry formats so there are now properties for:
* upper_left_counter_clockwise_vertices
* lower_left_counter_clockwise_vertices
* upper_right_counter_clockwise_vertices
* lower_right_counter_clockwise_vertices
... and there's a consistent logic for what counts as "up" for horizontal surfaces (it is always positive Y)
> fix(face): Add properties for all kinds of starting vertices

- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/geometry3d/plane.py
- tests/face3d_test.py
- tests/plane_test.py
There have been enough times where I can see that these properties would have saved us some extra code.
> fix(plane): Add properties for altitude and azimuth

- ladybug_geometry/geometry2d/polygon.py
Resolves https://github.com/ladybug-tools/ladybug-geometry/issues/335
> fix(polygon): Ensure that one duplicate vertex remains

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
Resolves https://github.com/ladybug-tools/ladybug-geometry/issues/362
> fix(polygon): Improve the performance of merge boundary and holes

- README.md
- ladybug_geometry/boolean.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/intersection2d.py
- ladybug_geometry/intersection3d.py
- ladybug_geometry/triangulation.py
- setup.py
- tests/face3d_test.py
- tests/polygon2d_test.py
This also add methods to split faces with one another as well as a method with improved performance for merging holes into boundaries.
> feat(boolean): Add module for polygon boolean operations

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
It seems that this is something that can get returned in certain cases.
> fix(boolean): Catch cases of degenerate Polygons from boolean

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- ladybug_geometry/intersection2d.py
- tests/face3d_test.py
Now I see they this math.is_close method is very useful.
> fix(intersection): Use better floating point tolerance check

- .github/workflows/ci.yaml
- ladybug_geometry/geometry2d/line.py
- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry2d/polyline.py
- tests/line2d_test.py
- tests/polyline2d_test.py
I am also fixing some bugs in Polyline2D.remove_colinear_vertices
> fix(polyline): Add methods to offset Polyline2D and LineSegment2D

- .github/workflows/ci.yaml
- .releaserc.json
- ladybug_geometry/_mesh.py
- ladybug_geometry/geometry2d/mesh.py
- ladybug_geometry/geometry3d/mesh.py
This commit also bumps the version of semantic release.
> fix(mesh): Update Mesh2D for consistency

- ladybug_geometry/geometry2d/polygon.py
- ladybug_geometry/geometry3d/face.py
- tests/face3d_test.py
The improvement will now check the collinearity on BOTH sides of the last vertex in order to determine whether it should be included.
> fix(colinear): Improve the check for inclusion of the last vertex
